---
- include: ./inotifylimit.yml
- include: ./oraclejdk8.yml
- get_url: url=https://download-cf.jetbrains.com/idea/ideaIC-2016.1.3.tar.gz
           dest=/vagrant/share/ideaIC-2016.1.3.tar.gz
           validate_certs=no
           sha256sum=d1cd3f9fd650c00ba85181da6d66b4b80b8e48ce5f4f15b5f4dc67453e96a179
  async: 1800
  poll: 10
- command: /bin/tar -zxf /vagrant/share/ideaIC-2016.1.3.tar.gz --directory=/opt
           creates=/opt/idea-IC-145.1617.8/bin
- file: path=/opt/ideaIC state=link src=/opt/idea-IC-145.1617.8
- file: path=/usr/local/bin/ideaIC.sh state=link src=/opt/ideaIC/bin/idea.sh
- file: path=/home/{{ username }}/Desktop
        state=directory
        mode=0700 owner={{ username }} group={{ username }}
- copy: src=../files/ideaIC.desktop
        dest=/home/{{ username }}/Desktop/ideaIC.desktop
        mode=0775 owner={{ username }} group={{ username }}
