---
- get_url: url=https://atom.io/download/deb
           dest=/vagrant/share/atom.deb
- apt: pkg={{ item }}
  with_items:
    - python-apt
    - aptitude
- apt: deb=/vagrant/share/atom.deb
       force=yes
  ignore_errors: yes
