---
- name: Install NVM
  shell: /usr/bin/curl --insecure https://raw.githubusercontent.com/creationix/nvm/master/install.sh | /bin/bash
         creates=/home/{{ username }}/.nvm/nvm.sh
         chdir=/home/{{ username }}
  sudo_user: "{{ username }}"
